### ISSUE TITLE
wrong cursor position on macOS

### ISSUE THREAD

**Issue by Capt-Lappland** [scanberg/viamd#73] opened 2024-06-19 11:49 UTC
Cursor coordinates are not being calculated correctly

Here's an image of the issue. The black box with details is where my cursor is, but the bond selected on the yellow box is far away.

Builded on MacBook Pro m2, tried both on macOS 17 and macOS 18 Beta. It seems not the problem with imgui.
![image](https://github.com/scanberg/viamd/assets/33972839/3abe55a6-5541-4b0d-a84f-87a49a5f8cd0)

**Comment by scanberg** [comment] 2024-06-20 13:54
Hi @Capt-Lappland,
Thanks for pointing this out.
I only have an old Macbook to test this on, but will attempt to debug this as best I can.
My theory is that the issue is related to DPI scaling not being correctly applied when performing the picking operation.

Best regards,
Robin

**Comment by scanberg** [comment] 2024-06-20 19:15
I think the issue is resolved in the latest commit.
It works on my older macbook at least and it was related to the DPI scaling.
If you can I would appreciate that you verify the fix on your machine as well before I close this issue.

Best regards,
Robin

**Comment by Capt-Lappland** [comment] 2024-06-21 08:21
Hi Robin,
It works perfectly on my m2 after applying fix.
Thank you for your quick reply.

Best wishes,
Runze
<img width="1680" alt="截屏2024-06-21 16 17 40" src="https://github.com/scanberg/viamd/assets/33972839/6387ffed-cca8-48af-80f4-76f406dc86f1">

**Closed** 2024-06-21 08:22 UTC
